using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEditor.Animations;
using UnityEngine;

namespace GDGGo.EditorTools
{
    /// <summary>
    /// Builds every prefab the game needs from the imported packs.
    ///
    /// Art sourcing is deliberate and evidence-based:
    ///   * <b>Vehicles, cones, buildings — Kenney.</b> Those FBX reference a
    ///     <c>colormap.png</c> that ships in the same folder, so they import textured.
    ///   * <b>Road, coin, signs — Quaternius.</b> Those packs contain no textures and no
    ///     vertex colours at all (checked against the source zips), so their meshes get
    ///     flat materials from <see cref="MaterialLibrary"/>. That is how those packs are
    ///     designed to be used — the colour lives in the material, not the mesh.
    ///
    /// Every prefab is built as: a plain root that owns the collider, physics and
    /// gameplay components, with the imported mesh parented underneath as a child named
    /// "Mesh". Keeping them separate means visual tweaks (rotating a car that faces the
    /// wrong way, nudging scale) never disturb the collider or the gameplay code.
    ///
    /// Idempotent: an existing prefab is left completely alone.
    /// </summary>
    public static class PrefabsBuilder
    {
        private const string Root = "Assets/Prefabs";
        private const string Kenney = "Assets/Models/Kenney";
        private const string Quaternius = "Assets/Models/Quaternius";

        /// <summary>
        /// Prefabs whose geometry comes from a Quaternius mesh, and which therefore bake
        /// in the source's orientation. <see cref="ModelAxisFixer"/> changes that
        /// orientation at import, but every Build* method skips a prefab that already
        /// exists — so without deleting these first, an axis fix would silently have no
        /// effect on the prefabs that most needed it.
        /// </summary>
        private static readonly string[] QuaterniusDerivedPrefabs =
        {
            $"{Root}/Road/Street_Straight.prefab",
            $"{Root}/Obstacles/Obstacle_StopSign.prefab",
            $"{Root}/Obstacles/Obstacle_TrafficLight.prefab",
            $"{Root}/Scenery/Prop_Streetlight.prefab",
            $"{Root}/Scenery/Prop_Tree.prefab",
            $"{Root}/Scenery/Prop_Bush.prefab",
            $"{Root}/Coin.prefab",
            // Legacy single power-up prefab (now superseded by per-type set).
            $"{Root}/PowerUp.prefab",
            $"{Root}/PowerUps/PowerUp_Magnet.prefab",
            $"{Root}/PowerUps/PowerUp_TwoX.prefab",
            $"{Root}/PowerUps/PowerUp_Shield.prefab",
            $"{Root}/PowerUps/PowerUp_Nitro.prefab",
            $"{Root}/PowerUps/PowerUp_Freeze.prefab",
            // Fuel: distinct RPG bottle prefab (was a Coin reuse).
            $"{Root}/PowerUps/Fuel.prefab",
        };

        /// <summary>
        /// Deletes the prefabs built from Quaternius meshes so the next BuildAll rebuilds
        /// them against the corrected axes. Safe to run at any time — everything it
        /// removes is regenerated by <see cref="BuildAll"/>.
        /// </summary>
        [MenuItem("GDG Go/2b. Rebuild Quaternius Prefabs", priority = 11)]
        public static void RebuildQuaterniusPrefabs()
        {
            DeleteQuaterniusDerivedPrefabs();
            BuildAll();
            SceneBuilder.BuildGameScene();   // scene holds direct references to them
        }

        /// <summary>
        /// Removes the Quaternius-derived prefabs so the next <see cref="BuildAll"/>
        /// regenerates them. Everything deleted here is rebuilt from source meshes.
        /// </summary>
        public static void DeleteQuaterniusDerivedPrefabs()
        {
            int deleted = 0;
            foreach (string path in QuaterniusDerivedPrefabs)
            {
                // Procedural meshes are written to a sibling "_Meshes.asset"; leaving it
                // behind would let a rebuilt prefab bind to the previous run's geometry.
                string meshPath = Path.ChangeExtension(path, null) + "_Meshes.asset";
                if (AssetDatabase.LoadMainAssetAtPath(meshPath) != null) AssetDatabase.DeleteAsset(meshPath);

                if (AssetDatabase.LoadAssetAtPath<GameObject>(path) == null) continue;
                if (AssetDatabase.DeleteAsset(path)) deleted++;
            }

            // Pedestrians too — same packs, same 100x scale.
            foreach (var (name, _) in PedestrianModels)
            {
                string path = $"{Root}/Pedestrians/{name}.prefab";
                if (AssetDatabase.LoadAssetAtPath<GameObject>(path) == null) continue;
                if (AssetDatabase.DeleteAsset(path)) deleted++;
            }

            // Old flat-disc glow materials (single _Glow.mat per pickup) and the new
            // two-layer _GlowCore/_GlowHalo variants. GetOrCreate returns existing
            // assets untouched, so leaving old additive-but-untextured glow mats in
            // place means the rebuilt prefabs would catch the old material and never
            // pick up the new radial-gradient textured ones. Deleting here forces
            // fresh creation on the next BuildAll().
            foreach (var (_, name, _, _, _, _, _) in PowerUpVariants)
            {
                DeleteGlowMaterials(name);
            }
            DeleteGlowMaterials("Fuel");

            AssetDatabase.Refresh();
            Debug.Log($"[PrefabsBuilder] Deleted {deleted} Quaternius-derived prefabs for rebuild.");
        }

        /// <summary>
        /// Deletes the old single "_Glow.mat" (flat horizontal-disc halo from the
        /// previous build) and the new "_GlowCore.mat" / "_GlowHalo.mat" pair so the
        /// next rebuild regenerates them from current code. Safe to call when none
        /// exist — DeleteAsset returns false for missing paths.
        /// </summary>
        private static void DeleteGlowMaterials(string name)
        {
            string[] candidates =
            {
                $"{MaterialLibrary.WorldFolder}/PowerUp_{name}_Glow.mat",
                $"{MaterialLibrary.WorldFolder}/PowerUp_{name}_GlowCore.mat",
                $"{MaterialLibrary.WorldFolder}/PowerUp_{name}_GlowHalo.mat",
                // Secondary painted-detail materials used by the new procedural
                // two-material icons (magnet red poles, shield white stripe,
                // secondary fallback). GetOrCreate returns the existing asset
                // untouched so a delete here is what forces the next BuildAll()
                // to regenerate them.
                $"{MaterialLibrary.WorldFolder}/PowerUp_{name}_Pole.mat",
                $"{MaterialLibrary.WorldFolder}/PowerUp_{name}_Stripe.mat",
                $"{MaterialLibrary.WorldFolder}/PowerUp_{name}_Secondary.mat",
            };
            foreach (string path in candidates)
            {
                if (AssetDatabase.LoadAssetAtPath<Material>(path) != null)
                    AssetDatabase.DeleteAsset(path);
            }
        }

        [MenuItem("GDG Go/2. Build All Prefabs", priority = 10)]
        public static void BuildAll()
        {
            // Tags must exist before any prefab tries to use them.
            ProjectSetup.EnsureTags();

            MaterialLibrary.EnsureFolder(Root);
            MaterialLibrary.EnsureFolder($"{Root}/Traffic");
            MaterialLibrary.EnsureFolder($"{Root}/Obstacles");
            MaterialLibrary.EnsureFolder($"{Root}/Road");
            MaterialLibrary.EnsureFolder($"{Root}/Scenery");

            int built = 0;

            built += BuildCoin() ? 1 : 0;
            // Per-type power-ups: 5 prefabs (was 1). See PowerUpVariants.
            // Fuel: distinct RPG bottle prefab so it doesn't reuse the coin disc.
            MaterialLibrary.EnsureFolder($"{Root}/PowerUps");
            BuildPowerUps(ref built);
            built += BuildFuelPrefab() ? 1 : 0;
            built += BuildPlayer() ? 1 : 0;
            built += BuildPolice() ? 1 : 0;

            // --- Traffic: Kenney vehicles, all textured. Speeds differ by class so
            //     overtaking a bus feels different from overtaking a hatchback. ---
            built += BuildTraffic("Traffic_Sedan", $"{Kenney}/CarKit/sedan.fbx") ? 1 : 0;
            built += BuildTraffic("Traffic_SUV", $"{Kenney}/CarKit/suv.fbx") ? 1 : 0;
            built += BuildTraffic("Traffic_Taxi", $"{Kenney}/CarKit/taxi.fbx") ? 1 : 0;
            built += BuildTraffic("Traffic_Van", $"{Kenney}/CarKit/van.fbx") ? 1 : 0;
            built += BuildTraffic("Traffic_Truck", $"{Kenney}/CarKit/truck.fbx") ? 1 : 0;
            built += BuildTraffic("Traffic_Delivery", $"{Kenney}/CarKit/delivery.fbx") ? 1 : 0;
            built += BuildTraffic("Traffic_Ambulance", $"{Kenney}/CarKit/ambulance.fbx") ? 1 : 0;
            built += BuildTraffic("Traffic_Firetruck", $"{Kenney}/CarKit/firetruck.fbx") ? 1 : 0;

            // --- Obstacles. Low ones can be jumped; tall ones must be dodged. ---
            built += BuildObstacle("Obstacle_Cone", $"{Kenney}/CarKit/cone.fbx", jumpable: true) ? 1 : 0;
            built += BuildObstacle("Obstacle_Tire", $"{Kenney}/CarKit/debris-tire.fbx", jumpable: true) ? 1 : 0;
            built += BuildObstacle("Obstacle_Door", $"{Kenney}/CarKit/debris-door.fbx", jumpable: true) ? 1 : 0;
            built += BuildObstacle("Obstacle_Box", $"{Kenney}/CarKit/box.fbx", jumpable: true) ? 1 : 0;
            // Quaternius props import at 100x (see the scale constants above), so these
            // are small numbers rather than large ones: a stop sign delivered 53.8 units
            // tall needs 0.0558 to reach a roadside 3 units.
            built += BuildObstacle("Obstacle_StopSign", $"{Quaternius}/ModularStreets/Sign_Stop.fbx", jumpable: false, MaterialLibrary.Metal(), scale: StopSignScale, upright: true) ? 1 : 0;
            built += BuildObstacle("Obstacle_TrafficLight", $"{Quaternius}/ModularStreets/TrafficLight.fbx", jumpable: false, MaterialLibrary.Metal(), scale: TrafficLightScale, upright: true) ? 1 : 0;

            // --- Road tiles. Quaternius, so they need a palette. ---
            built += BuildRoadTile("Street_Straight", $"{Quaternius}/ModularStreets/Street_Straight.fbx") ? 1 : 0;

            // --- Scenery. Kenney city kits, textured. ---
            BuildSceneryBatch(ref built);

            // --- Pedestrians. Quaternius character packs. ---
            BuildPedestrianBatch(ref built);

            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
            Debug.Log($"[PrefabsBuilder] Done — {built} prefab(s) created (existing ones left untouched).");
        }

        // ==================================================================
        // Individual builders
        // ==================================================================

        private static bool BuildCoin()
        {
            string path = $"{Root}/Coin.prefab";
            if (Exists(path)) return false;

            GameObject root = NewRoot("Coin");
            GameObject mesh = AttachMesh(root, $"{Quaternius}/RPG/Coin.fbx", scale: CoinScale, upright: true);
            if (mesh == null) { Object.DestroyImmediate(root); return false; }

            // Single "Gold" material slot on this mesh; the spawner overwrites it per type.
            MaterialLibrary.AssignPalette(mesh, MaterialLibrary.GetOrCreate(
                $"{MaterialLibrary.CoinsFolder}/CoinRed.mat", new Color(0.918f, 0.263f, 0.208f)));

            // No rotation. The FBX's own node transform already stands the disc upright
            // (73.7 x 73.8 wide, 18.1 thick once imported), so it faces the player as-is.
            // The previous 90-degree X rotation here tipped it flat, which is why coins
            // rendered as white plates lying on the road.

            var collider = root.AddComponent<BoxCollider>();
            collider.isTrigger = true;
            // Deliberately generous, and deliberately NOT fitted to the mesh: a coin is a
            // reward, so its pickup volume should be forgiving. Cubic so it catches the
            // player at any approach angle.
            collider.size = new Vector3(1.9f, 1.9f, 1.9f);

            var pickup = root.AddComponent<Coins.CoinPickup>();
            pickup.coinMeshRenderer = mesh.GetComponentInChildren<MeshRenderer>(true);

            MakeMovingTrigger(root);

            return Save(root, path);
        }

        /// <summary>
        /// One imported-pack mesh per power-up type. Replaces the earlier
        /// procedurally-authored icons (see <c>PowerUpMeshBuilder</c>, now
        /// orphaned on disk) with real silhouettes sourced from Kenney and
        /// Quaternius packs so the mesh reads as the gameplay effect it
        /// performs — a Subway-Surfers-style crane magnet for CoinMagnet,
        /// a star for TwoX, a warrior shield for Shield, a propane cylinder
        /// for Nitro, a 6-arm snowflake for PoliceFreeze.
        ///
        /// Sourcing (2026-08-17):
        ///   Magnet      Kenney Factory Kit        FactoryKit/crane-magnet.fbx
        ///   TwoX        Kenney Platformer Kit     PlatformerKit/star.fbx
        ///   Shield      Kenney Mini Dungeon       MiniDungeon/shield-round.fbx
        ///   Nitro       Quaternius Survival       Survival/PropaneTank.blend
        ///   Freeze      Kenney Holiday Kit        HolidayKit/snowflake-a.fbx
        ///
        /// Two of the icons (Magnet, Shield) ship multiple material slots;
        /// the imported FBXs render with whatever materials the pack bundles.
        /// This builder overrides those per-renderer with the icon's tint +
        /// secondary materials so every power-up reads at game-speed as the
        /// identity colour the player has been trained to expect (magnet =
        /// gold body + red poles, etc.). Single-slot icons (TwoX, Nitro,
        /// Freeze) override the lone renderer with the tint.
        ///
        /// <see cref="ImportScale"/> is per-entry because the packs author at
        /// wildly different scales. Kenney FBXs carry no node transform and
        /// import 1:1 (see CLAUDE.md §3a), so a Kenney icon's authored height
        /// arrives in world units directly — the values below normalise each
        /// picked mesh to <b>1 world unit tall</b> (verified by measuring
        /// Renderer.bounds in Unity MCP, 2026-08-17): 1 / bounds.size.y.
        ///
        /// <see cref="Upright"/> is true only for Z-up Quaternius sources
        /// (the Survival <c>.blend</c> files, which the existing
        /// <see cref="GDGGo.EditorTools.ModelAxisFixer"/> engine treats as
        /// Quaternius props requiring the <c>-90 X</c> "stand it up" rotation).
        /// Kenney FBXs are already Y-up — passing upright=true would tip
        /// them onto their sides.
        /// </summary>
        private static readonly (PowerUps.PowerUpType Type, string Name, Color Hue,
                                 bool HasSecondary, string FbxPath,
                                 float ImportScale, bool Upright)[] PowerUpVariants =
        {
            (PowerUps.PowerUpType.CoinMagnet,    "Magnet",  new Color(0.98f, 0.74f, 0.02f), true,
                                             $"{Kenney}/FactoryKit/crane-magnet.fbx", 1.11f, false),
            (PowerUps.PowerUpType.TwoX,         "TwoX",    new Color(0.20f, 0.85f, 0.35f), false,
                                             $"{Kenney}/PlatformerKit/star.fbx", 2.75f, false),
            (PowerUps.PowerUpType.Shield,       "Shield",  new Color(0.26f, 0.52f, 0.96f), true,
                                             $"{Kenney}/MiniDungeon/shield-round.fbx", 2.63f, false),
            (PowerUps.PowerUpType.Nitro,        "Nitro",   new Color(0.20f, 0.90f, 1.00f), false,
                                             $"{Quaternius}/Survival/PropaneTank.blend", 0.0069f, true),
            (PowerUps.PowerUpType.PoliceFreeze, "Freeze",  new Color(0.85f, 0.35f, 0.95f), false,
                                             $"{Kenney}/HolidayKit/snowflake-a.fbx", 2.50f, false),
        };

        /// <summary>
        /// Builds one prefab per power-up type, each loading its own imported
        /// mesh from a Kenney or Quaternius pack (see <see cref="PowerUpVariants"/>).
        /// The silhouette — not just the colour — tells the player what they are
        /// grabbing: a crane magnet for CoinMagnet, a star for TwoX, a warrior
        /// shield for Shield, a propane cylinder for Nitro, a snowflake for PoliceFreeze.
        ///
        /// Each imported mesh arrives with whatever material slots the pack
        /// bundled; we override the per-renderer shared materials with our
        /// tint + secondary (for two-slot icons) so every pickup reads at
        /// game-speed as the identity colour the player has been trained to
        /// expect — magnet gold + red poles, shield blue + silver stripe, etc.
        ///
        /// Each prefab carries the same collider + components the old one did —
        /// only the mesh differs — so <see cref="PowerUps.PowerUpEffect"/> and
        /// <see cref="PowerUps.PowerUpSpawner"/> plug in unchanged. Idempotent:
        /// existing prefabs are left alone, so this stays safe under "Run Full
        /// Project Setup" re-runs.
        /// </summary>
        private static int BuildPowerUps(ref int built)
        {
            foreach (var (type, name, hue, hasSecondary, fbxPath, importScale, upright) in PowerUpVariants)
            {
                string path = $"{Root}/PowerUps/PowerUp_{name}.prefab";
                if (Exists(path)) { continue; }

                GameObject rootObj = NewRoot($"PowerUp_{name}");

                // Imported silhouette from a real pack mesh. Kenney FBXs ship
                // Y-up 1:1 (no node transform); Quaternius .blend files are
                // Z-up centimetre-scale and the existing ModelAxisFixer ×100
                // pre-scale brings them to metre world units at import.
                // Per-entry ImportScale then normalises each picked mesh to
                // exactly 1 world unit tall (verified via Renderer.bounds).
                // Upright applies the -90 X rotation only for Z-up Quaternius
                // sources — Kenney is already Y-up, so passing it would tip
                // those meshes onto their sides.
                GameObject meshGo = AttachMesh(rootObj, fbxPath, importScale, upright);
                if (meshGo == null)
                {
                    Object.DestroyImmediate(rootObj);
                    Debug.LogWarning($"[PrefabsBuilder] AttachMesh returned null for {name} ({fbxPath}) — PowerUp_{name} not built.");
                    continue;
                }

                // Primary tint material — the icon body. Pumped emission (×2.2)
                // reads as self-lit even in shadow under Built-in (no Bloom).
                // Combined with the halo below, a power-up now reads as *glowing*
                // rather than just bright-tinted.
                Material tintMat = MaterialLibrary.GetOrCreate(
                    $"{MaterialLibrary.WorldFolder}/PowerUp_{name}.mat", hue, 0.85f, 0.4f);
                MaterialLibrary.SetEmission(tintMat, hue * 2.2f);

                // Secondary material — used by the two-material icons (magnet red
                // poles, shield silver stripe). Single-material icons (star,
                // cylinder, snowflake) skip the secondary assignment.
                Material secondaryMat = null;
                if (hasSecondary)
                {
                    secondaryMat = SecondaryPowerUpMaterial(type, name, hue);
                }

                // Override the imported pack-bundled materials with our tint +
                // secondary. The proc-gen builder used "_A"/"_B" child-naming to
                // distinguish slots; imported FBXs don't follow that convention,
                // so for two-slot icons we treat the first renderer found as the
                // primary body and the second as the secondary detail. A single
                // renderer always gets the tint. Order is the natural
                // GetComponentsInChildren order, which matches the FBX's child
                // export order — the same order the pack's own colours use.
                var renderers = meshGo.GetComponentsInChildren<MeshRenderer>(true);
                for (int i = 0; i < renderers.Length; i++)
                {
                    if (hasSecondary && i > 0)
                        renderers[i].sharedMaterial = secondaryMat;
                    else
                        renderers[i].sharedMaterial = tintMat;
                }

                // Additive glow halo — a two-layer billboarded radial glow (bright
                // core + soft halo) sibling of the mesh, so it tracks the camera
                // while the silhouette spins on Y. The Subway-Surfers read: a true
                // soft glow halo around the floating object, not a flat disc.
                AddGlowHalo(rootObj, name, hue, meshGo);

                var collider = rootObj.AddComponent<BoxCollider>();
                collider.isTrigger = true;
                collider.size = new Vector3(2f, 2f, 2f);

                var effect = rootObj.AddComponent<PowerUps.PowerUpEffect>();
                effect.type = type;
                // tintTarget points at the FIRST renderer found — Configure() will tint
                // all of them via the shared material anyway, and we set the tint above
                // so an absent tintTarget is a null-op, not a loss of colour.
                effect.tintTarget = meshGo.GetComponentInChildren<MeshRenderer>(true);

                rootObj.AddComponent<PowerUps.RotateSlow>();

                MakeMovingTrigger(rootObj);

                if (Save(rootObj, path)) built++;
            }
            return built;
        }

        /// <summary>
        /// Builds (or returns an existing) the *secondary* material for two-part
        /// icons — the painted detail on top of the icon body. Different per
        /// power-up so the silhouette has a clear two-colour read:
        ///   Magnet poles — pure Google Red #EA4335 (universal N/S pole marker)
        ///   Shield stripe — near-white (universal heraldic crest colour)
        ///   (Fuel handled by BuildFuelPrefab with its own darker-orange cap mat.)
        /// The secondary is intentionally NOT emissive — it reads as a painted
        /// detail on the icon, not a second light source.
        /// </summary>
        private static Material SecondaryPowerUpMaterial(PowerUps.PowerUpType type, string name, Color hue)
        {
            switch (type)
            {
                case PowerUps.PowerUpType.CoinMagnet:
                    // Magnet poles — pure Google Red.
                    return MaterialLibrary.GetOrCreate(
                        $"{MaterialLibrary.WorldFolder}/PowerUp_{name}_Pole.mat",
                        new Color(0.918f, 0.200f, 0.208f), 0.6f, 0.05f);

                case PowerUps.PowerUpType.Shield:
                    // Shield crest stripe — near-white with low specular so it
                    // doesn't read as a mirror under the directional light.
                    return MaterialLibrary.GetOrCreate(
                        $"{MaterialLibrary.WorldFolder}/PowerUp_{name}_Stripe.mat",
                        new Color(0.92f, 0.92f, 0.92f), 0.4f, 0.0f);

                default:
                    // Two-material path is only used by Magnet and Shield; fall
                    // back to the primary hue so any future added pair stays
                    // single-hued.
                    return MaterialLibrary.GetOrCreate(
                        $"{MaterialLibrary.WorldFolder}/PowerUp_{name}_Secondary.mat",
                        hue, 0.6f, 0.0f);
            }
        }

        /// <summary>
        /// Builds the fuel pickup prefab from the Quaternius Survival pack's
        /// <c>GasCan.blend</c> — a real jerry-can silhouette sourced from an
        /// imported pack. Fuel previously reused the Coin mesh + an orange
        /// material; a canister reads as "a canister" rather than "another
        /// coin", which is the exact problem CLAUDE.md §Fuel warns about: a
        /// fuel can that reads as another coin defeats the mechanic.
        ///
        /// The imported <c>GasCan</c> mesh ships with Quaternius Survival's
        /// own materials; we override the per-renderer shared materials with
        /// our hot-orange body and a darker orange cap so the can reads as a
        /// two-tone glowing pickup regardless of the bundled pack texture.
        ///
        /// The CoinPickup + CoinSpawner integration uses <see cref="CoinType.Fuel"/>
        /// for the score/fuel short-circuit; we set that on the prefab so a pickup
        /// of any fuel instance routes correctly without the spawner having to
        /// tag it.
        /// </summary>
        public static bool BuildFuelPrefab()
        {
            string path = $"{Root}/PowerUps/Fuel.prefab";
            if (Exists(path)) return false;

            GameObject rootObj = NewRoot("Fuel");

            // Quaternius Survival's GasCan.blend is a real jerry-can silhouette.
            // ModelAxisFixer pre-applies ×100 import scale (Survival is under
            // Assets/Models/Quaternius/, so it's treated as a Quaternius prop),
            // bringing the can to ~124 world units tall post-×100. Per-entry
            // scale of 1/124 = 0.0080f normalises the can to ~1 world unit
            // tall (verified via Renderer.bounds in Unity MCP). Upright pass
            // applies the -90 X rotation that stands the Z-up blend file up
            // on Y, then re-seats the base onto y = 0 so the can floats
            // cleanly above the glow halo instead of half-burying inside it.
            GameObject meshGo = AttachMesh(
                rootObj, $"{Quaternius}/Survival/GasCan.blend", scale: 0.0080f, upright: true);
            if (meshGo == null)
            {
                Object.DestroyImmediate(rootObj);
                Debug.LogWarning("[PrefabsBuilder] AttachMesh returned null for GasCan.blend — Fuel prefab not built.");
                return false;
            }

            // Fuel is deliberately outside the Google Palette: hot orange
            // (#FF6B0D) so it doesn't read as "another coin".
            Color fuelOrange = new Color(1.0f, 0.42f, 0.05f);
            Material liquidMat = MaterialLibrary.GetOrCreate(
                $"{MaterialLibrary.WorldFolder}/Fuel.mat", fuelOrange, 0.55f, 0.0f);
            // Pumped emission (×1.6 was ×0.9) — same reasoning as BuildPowerUps:
            // under Built-in without Bloom, emission just brightens the lit
            // surface, so the halo plus a stronger emission is what makes a fuel
            // can read as glowing.
            MaterialLibrary.SetEmission(liquidMat, fuelOrange * 1.6f);

            // Darker orange for the cap + handle so the can reads as a two-tone
            // object — the silhouette stays unambiguous from any angle.
            Material capMat = MaterialLibrary.GetOrCreate(
                $"{MaterialLibrary.WorldFolder}/Fuel_Cap.mat",
                new Color(0.68f, 0.28f, 0.04f), 0.6f, 0.0f);

            // Override the imported GasCan's bundled materials with our hot-orange
            // body + dark orange cap. The proc-gen builder used "_A"/"_B" child
            // naming to distinguish slots; the imported blend file doesn't follow
            // that convention, so the first MeshRenderer carries the body and
            // every subsequent renderer carries the cap. A single-renderer can
            // stays single-material (the whole can reads as hot orange).
            var renderers = meshGo.GetComponentsInChildren<MeshRenderer>(true);
            for (int i = 0; i < renderers.Length; i++)
            {
                renderers[i].sharedMaterial = (i > 0) ? capMat : liquidMat;
            }

            AddGlowHalo(rootObj, "Fuel", fuelOrange, meshGo);

            var collider = rootObj.AddComponent<BoxCollider>();
            collider.isTrigger = true;
            // Generous pickup volume — a fuel can is a milestone, not a tight grab.
            collider.size = new Vector3(1.6f, 1.8f, 1.6f);

            var pickup = rootObj.AddComponent<Coins.CoinPickup>();
            // Pre-tag the prefab instance so an unconfigured spawner still routes a
            // fuel pickup as fuel — the field is normally written by CoinSpawner at
            // spawn time, but pre-tagging is a safety belt and is cheap.
            pickup.coinType = Coins.CoinType.Fuel;
            pickup.coinValue = 0;
            pickup.coinMeshRenderer = meshGo.GetComponentInChildren<MeshRenderer>(true);

            MakeMovingTrigger(rootObj);

            return Save(rootObj, path);
        }

        /// <summary>
        /// Builds the Subway-Surfers-style two-layer glow halo for a floating power-up:
        ///
        ///   Glow (root sibling of "Mesh" — never rotates with the silhouette spin)
        ///   ├─ BrightCore   — 1.3× mesh bounds, bright tint. The "energy spike" centre.
        ///   └─ SoftHalo     — 2.8× mesh bounds, faint tint. The wide diffuse aura.
        ///
        /// Both layers are billboarded quads textured with a radial-gradient PNG
        /// (white core fading to transparent at the quad edge), blended
        /// additively. The billboard component guarantees the glow always
        /// presents a full circle to the camera regardless of viewing angle, and
        /// the radial sprite gives a smooth soft falloff that reads as a true
        /// volumetric glow rather than a flat plate.
        ///
        /// Why two layers: Subway Surfers power-ups read as the object floating
        /// inside a **glowing fog**. One layer with a single tint either washes
        /// the centre out white (too bright) or fails to bleed past the
        /// silhouette (too dim). The tight bright core plus wide faint halo is
        /// the only configuration that reads under both peripheral vision and
        /// direct gaze.
        ///
        /// The glow rig is parented DIRECTLY to the pickup root rather than to
        /// the "Mesh" child. The mesh's <see cref="RotateSlow"/> spins it on Y,
        /// and letting the halo ride along would smear the billboarded sprite
        /// into a spinning plate — the exact horizontal-disc look players
        /// reject. A direct-root sibling means the billboard live-tracks the
        /// camera independently, so the halo stays a steady sphere around the
        /// spinning silhouette.
        /// </summary>
        private static void AddGlowHalo(GameObject root, string name, Color hue, GameObject mesh)
        {
            // Measure the mesh's bounds so the halo size scales per pickup — a magnet
            // and an arrow have different silhouettes, so the glow ring around them
            // should too.
            float meshSize = 1f;
            if (mesh != null)
            {
                var renderers = mesh.GetComponentsInChildren<Renderer>(true);
                if (renderers.Length > 0)
                {
                    Bounds b = renderers[0].bounds;
                    for (int i = 1; i < renderers.Length; i++) b.Encapsulate(renderers[i].bounds);
                    meshSize = Mathf.Max(b.size.x, b.size.y, b.size.z);
                    if (meshSize < 0.8f) meshSize = 0.8f;
                }
            }

            // Outer rig holding both halo sprites. Parented to root (NOT to the
            // spinning mesh child) so the billboards track the camera independently.
            var rig = new GameObject("GlowHalo");
            rig.transform.SetParent(root.transform, false);
            rig.transform.localPosition = Vector3.zero;
            rig.transform.localRotation = Quaternion.identity;
            rig.transform.localScale = Vector3.one;

            // Shared radial texture asset. Created at first build, reused after.
            const string glowTexPath = "Assets/Textures/Glow/GlowRadial.png";

            // Bright core — 1.3× mesh bounds, near full-intensity tint.
            Color brightTint = new Color(hue.r * 2.5f, hue.g * 2.5f, hue.b * 2.5f, 1.0f);
            Material brightMat = MaterialLibrary.GetOrCreateTexturedGlow(
                $"{MaterialLibrary.WorldFolder}/PowerUp_{name}_GlowCore.mat",
                glowTexPath, brightTint);
            BuildGlowSprite(rig.transform, "BrightCore", meshSize * 1.3f, brightMat);

            // Soft halo — 2.8× mesh bounds, fainter tint.
            Color haloTint = new Color(hue.r * 1.4f, hue.g * 1.4f, hue.b * 1.4f, 0.55f);
            Material haloMat = MaterialLibrary.GetOrCreateTexturedGlow(
                $"{MaterialLibrary.WorldFolder}/PowerUp_{name}_GlowHalo.mat",
                glowTexPath, haloTint);
            // Render the soft halo first so the bright core overlays it.
            GameObject haloSprite = BuildGlowSprite(rig.transform, "SoftHalo", meshSize * 2.8f, haloMat);
            haloSprite.transform.SetAsFirstSibling();
        }

        /// <summary>
        /// Builds one billboarded quad child of <paramref name="parent"/>: a 1×1
        /// quad centred on the origin, facing +Z, scaled by <paramref name="size"/>
        /// on X and Y. A <see cref="PowerUps.Billboard"/> component makes the quad
        /// live-track the main camera each frame so the radial quad always
        /// presents a circle to the player.
        /// </summary>
        private static GameObject BuildGlowSprite(Transform parent, string spriteName, float size, Material mat)
        {
            var go = new GameObject(spriteName);
            go.transform.SetParent(parent, false);
            go.transform.localPosition = Vector3.zero;
            go.transform.localRotation = Quaternion.identity;
            go.transform.localScale = new Vector3(size, size, 1f);

            var filter = go.AddComponent<MeshFilter>();
            filter.sharedMesh = BuildQuadMesh($"PowerUp_GlowMesh_{spriteName}");

            var renderer = go.AddComponent<MeshRenderer>();
            renderer.sharedMaterial = mat;
            // Additive glow must depth-write OFF so it never occludes the mesh or
            // anything between the halo and the camera; shadow casting and probes
            // are pure noise on a transparent additive quad.
            renderer.shadowCastingMode = UnityEngine.Rendering.ShadowCastingMode.Off;
            renderer.receiveShadows = false;
            renderer.lightProbeUsage = UnityEngine.Rendering.LightProbeUsage.Off;
            renderer.reflectionProbeUsage = UnityEngine.Rendering.ReflectionProbeUsage.Off;

            // Billboard component: makes the quad face the camera every frame.
            // Full free-rotation billboard (lockYAxis=false) gives the true
            // Subway-Surfers "always a sphere" read.
            var billboard = go.AddComponent<PowerUps.Billboard>();
            billboard.lockYAxis = false;

            return go;
        }

        /// <summary>
        /// Builds (and stores on the prefab asset via AddObjectToAsset in <see cref="Save"/>)
        /// a unit quad centred on the origin and facing +Z. Used by <see cref="AddGlowHalo"/>
        /// as the halo geometry — a literal 1×1 plane, the halo rotation + scale moulds it.
        /// </summary>
        private static Mesh BuildQuadMesh(string name)
        {
            var mesh = new Mesh { name = name };
            mesh.vertices = new Vector3[]
            {
                new Vector3(-0.5f, -0.5f, 0f),
                new Vector3( 0.5f, -0.5f, 0f),
                new Vector3( 0.5f,  0.5f, 0f),
                new Vector3(-0.5f,  0.5f, 0f),
            };
            mesh.uv = new Vector2[]
            {
                new Vector2(0f, 0f),
                new Vector2(1f, 0f),
                new Vector2(1f, 1f),
                new Vector2(0f, 1f),
            };
            mesh.triangles = new int[] { 0, 2, 1, 0, 3, 2 };
            mesh.RecalculateNormals();
            return mesh;
        }

        /// <summary>The bodies offered on the Car Select screen. Ids must match there.</summary>
        public static readonly (string Id, string Label, string Fbx)[] SelectableCars =
        {
            ("sports",  "Sports",  "CarKit/sedan-sports.fbx"),
            ("race",    "Racer",   "CarKit/race.fbx"),
            ("suv",     "SUV",     "CarKit/suv-luxury.fbx"),
            ("taxi",    "Taxi",    "CarKit/taxi.fbx"),
        };

        private static bool BuildPlayer()
        {
            string path = $"{Root}/PlayerCar.prefab";
            if (Exists(path)) return false;

            GameObject root = NewRoot("PlayerCar");
            SafeSetTag(root, Tags.Player);

            // Every selectable body lives on the prefab; PlayerCarSkin enables one.
            // Sharing one collider across all of them keeps the hitbox identical
            // whichever car you pick — a cosmetic choice must not be a balance choice.
            var skins = new List<Gameplay.PlayerCarSkin.Skin>();
            GameObject firstMesh = null;

            foreach ((string id, string _, string fbx) in SelectableCars)
            {
                GameObject mesh = AttachMesh(root, $"{Kenney}/{fbx}", scale: 1f);
                if (mesh == null) continue;

                mesh.name = "Mesh_" + id;
                if (firstMesh == null) firstMesh = mesh; else mesh.SetActive(false);
                skins.Add(new Gameplay.PlayerCarSkin.Skin { id = id, meshRoot = mesh });
            }

            if (firstMesh == null) { Object.DestroyImmediate(root); return false; }

            var collider = root.AddComponent<BoxCollider>();
            collider.isTrigger = true;
            collider.size = new Vector3(1.7f, 1.1f, 3.4f);
            collider.center = new Vector3(0f, 0.55f, 0f);

            // Kinematic so nothing pushes the car around, but present so Unity delivers
            // OnTrigger messages against the static trigger colliders on pickups/hazards.
            var body = root.AddComponent<Rigidbody>();
            body.isKinematic = true;
            body.useGravity = false;

            var car = root.AddComponent<Gameplay.PlayerCar>();
            car.meshRoot = firstMesh.transform;

            var collision = root.AddComponent<Gameplay.PlayerCollision>();
            collision.flashRenderers = firstMesh.GetComponentsInChildren<Renderer>(true);

            var skin = root.AddComponent<Gameplay.PlayerCarSkin>();
            skin.skins = skins.ToArray();

            return Save(root, path);
        }

        private static bool BuildPolice()
        {
            string path = $"{Root}/PoliceCar.prefab";
            if (Exists(path)) return false;

            GameObject root = NewRoot("PoliceCar");
            GameObject mesh = AttachMesh(root, $"{Kenney}/CarKit/police.fbx", scale: 1f);
            if (mesh == null) { Object.DestroyImmediate(root); return false; }

            var ai = root.AddComponent<Police.PoliceAI>();
            ai.barRed = MakeBarLight(root, "LightBarRed", new Color(1f, 0.15f, 0.15f), -0.5f);
            ai.barBlue = MakeBarLight(root, "LightBarBlue", new Color(0.2f, 0.35f, 1f), 0.5f);

            // No collider: the police car is a threat indicator, never a thing you hit.
            // Heat reaching zero is what ends the run.
            return Save(root, path);
        }

        private static Light MakeBarLight(GameObject parent, string name, Color color, float xOffset)
        {
            var go = new GameObject(name);
            go.transform.SetParent(parent.transform, false);
            go.transform.localPosition = new Vector3(xOffset, 1.5f, 0f);

            var light = go.AddComponent<Light>();
            light.type = LightType.Point;
            light.color = color;
            light.intensity = 4.5f;
            light.range = 14f;
            light.shadows = LightShadows.None;   // point-light shadows are costly on WebGL
            return light;
        }

        private static bool BuildTraffic(string name, string fbxPath)
        {
            string path = $"{Root}/Traffic/{name}.prefab";
            if (Exists(path)) return false;

            GameObject root = NewRoot(name);
            GameObject mesh = AttachMesh(root, fbxPath, scale: 1f);
            if (mesh == null) { Object.DestroyImmediate(root); return false; }

            SafeSetTag(root, Tags.Obstacle);

            var collider = root.AddComponent<BoxCollider>();
            collider.isTrigger = true;
            collider.size = new Vector3(1.8f, 1.3f, 3.8f);
            collider.center = new Vector3(0f, 0.6f, 0f);

            // Traffic is tall — a jump must not clear it, or lane changes stop mattering.
            var obstacle = root.AddComponent<Obstacles.Obstacle>();
            obstacle.clearableByJump = false;

            root.AddComponent<Traffic.TrafficCar>();

            MakeMovingTrigger(root);

            return Save(root, path);
        }

        private static bool BuildObstacle(string name, string fbxPath, bool jumpable,
                                          Material palette = null, float scale = 1f, bool upright = false)
        {
            string path = $"{Root}/Obstacles/{name}.prefab";
            if (Exists(path)) return false;

            GameObject root = NewRoot(name);
            GameObject mesh = AttachMesh(root, fbxPath, scale, upright);
            if (mesh == null) { Object.DestroyImmediate(root); return false; }

            if (palette != null) MaterialLibrary.AssignPalette(mesh, palette, MaterialLibrary.RoadLine());

            SafeSetTag(root, Tags.Obstacle);

            var collider = root.AddComponent<BoxCollider>();
            collider.isTrigger = true;
            // Fit the trigger to what is actually drawn. A hardcoded box is how you get
            // an obstacle you crash into before you reach it, or one you drive through:
            // these meshes differ hugely in size (a cone is under a metre, a traffic
            // light over four) and the prefab scale differs per pack.
            FitTriggerToMesh(collider, mesh,
                fallback: jumpable ? new Vector3(1.3f, 0.9f, 1.3f) : new Vector3(1.4f, 3.2f, 1.4f));

            var obstacle = root.AddComponent<Obstacles.Obstacle>();
            obstacle.clearableByJump = jumpable;

            MakeMovingTrigger(root);

            return Save(root, path);
        }

        /// <summary>
        /// Width of a road tile, in world units, after <see cref="RoadTileScale"/>.
        /// Three lanes at <c>LaneModel.LaneWidth</c> (3.0) plus a margin each side so the
        /// outer lanes are not flush with the kerb.
        ///
        /// The tile is square, so this is also its length along Z — which is what
        /// <c>RoadScroller.tileLength</c> must be set to.
        /// </summary>
        public const float RoadTileWidth = 12f;

        /// <summary>
        /// Scale that brings a rotated road tile to <see cref="RoadTileWidth"/> on Z.
        ///
        /// Measured inside Unity, not inferred from the file: with the importer set to
        /// <c>globalScale = 100</c> the tile delivers as <b>200 x 200 x 25</b>, and after
        /// <see cref="QuaterniusUprightRotation"/> it is <b>200 x 25 x 200</b> — 200 wide,
        /// 25 thick, 200 long. 12/200 = 0.06 gives a 12 x 1.5 x 12 tile.
        /// </summary>
        public const float RoadTileSourceSize = 200f;
        public const float RoadTileScale = RoadTileWidth / RoadTileSourceSize;

        // ------------------------------------------------------------------
        // Quaternius orientation and scale — every number here was MEASURED in the
        // editor via Renderer.bounds, never derived from the FBX file's bytes.
        //
        // Two properties of these packs drive everything:
        //
        //  1. UNITS. The mesh data is authored tiny (Street_Straight's Mesh.bounds is
        //     0.02 x 0.02 x 0.0025) and `useFileScale` honours it, so at the default
        //     import settings every prop arrives at ~1/100th of usable size. The
        //     importers are set to `globalScale = 100, useFileScale = false` — see
        //     ModelAxisFixer. The props/streets/RPG packs need this; the character
        //     packs do NOT (they are already metre-scale) and are exempted there.
        //
        //  2. ORIENTATION. Props are authored Z-up, so their tallest extent lands on Z
        //     and they lie on their side unless rotated -90 on X. Measured as-is:
        //
        //       Street_Straight  200.00 x 200.00 x  25.00   -> -90X -> 200 x 25 x 200
        //       Coin              73.67 x  18.12 x  73.77   -> -90X ->  74 x 74 x 18
        //       Sign_Stop          2.33 x  13.84 x  53.77   -> -90X
        //       TrafficLight      12.30 x   8.96 x  87.09   -> -90X
        //       Streetlight      13.17 x  13.17 x 109.04    -> -90X
        //       Tree1            206.73 x 298.78 x 409.91   -> -90X
        //       Bush1            107.42 x 107.41 x 149.12   -> -90X
        //       Male_Casual        1.96 x   4.93 x   1.13   -> already upright, no rot
        //
        // Scale = target size / measured size on the axis that defines the object:
        //
        //   prefab        measured after -90X        target        scale
        //   Coin           73.67 wide                1.3 wide     0.01765
        //   PowerUp        73.67 wide                1.7 wide     0.02308
        //   StopSign       53.77 tall                2.6 tall     0.04835
        //   TrafficLight   87.09 tall                4.2 tall     0.04823
        //   Streetlight   109.04 tall                6.5 tall     0.05961
        //   Tree          409.91 tall                6.5 tall     0.01586
        //   Bush          149.12 tall                1.5 tall     0.01006
        //   Pedestrian      4.93 tall (no rot)       1.8 tall     0.36518
        // ------------------------------------------------------------------

        /// <summary>
        /// Stands a Z-up Quaternius prop upright. Applied to the mesh child, never to the
        /// prefab root — the root owns the collider, and rotating it would tip the hitbox
        /// out of alignment with the lanes.
        /// </summary>
        private static readonly Quaternion QuaterniusUprightRotation = Quaternion.Euler(-90f, 0f, 0f);

        /// <summary>
        /// The road tile needs the upright rotation <i>and</i> a quarter turn on Y.
        ///
        /// The street mesh is authored running along X. After only the -90 X correction
        /// its lane-marking submesh measures 200 x 2 x 6 in world space — 200 units long
        /// across the player's path — so the dashes run sideways like a zebra crossing.
        /// Adding 90 on Y turns that to 6 x 2 x 200, i.e. along the direction of travel,
        /// which is what makes it read as a road instead of a paved square.
        /// </summary>
        private static readonly Quaternion RoadTileRotation = Quaternion.Euler(-90f, 90f, 0f);

        // Coin diameter 0.9 against a 1.5-wide car: big enough to read at speed, small
        // enough that three abreast in a lane still look like collectables rather than
        // roadblocks. Measured source is 73.67 wide, so 0.9/73.67.
        private const float CoinScale = 0.01222f;
        private const float StopSignScale = 0.04835f;
        private const float TrafficLightScale = 0.04823f;
        private const float StreetlightScale = 0.05961f;
        private const float TreeScale = 0.01586f;
        private const float BushScale = 0.01006f;

        // Power-up scales — RETIRED. The Quaternius RPG power-up meshes (heart,
        // star, armor, arrow, snowflake, potion) were replaced by procedurally-
        // authored icons in PowerUpMeshBuilder. Each procedural icon is authored
        // at exactly 1 unit tall with its lowest vertex at y = 0, so no
        // per-FBX import-scale constant is needed. The Coin prefab still uses
        // Quaternius/RPG/Coin.fbx (see CoinScale, defined next to BuildCoin).

        /// <summary>
        /// Builds the road tile from scratch instead of using the Quaternius street mesh.
        ///
        /// The pack mesh was measured and rejected: it is a coarse quad strip with
        /// vertices only at x = -6, -2, 0, +2, +6, and its centre band sits 0.18 units
        /// LOWER than the rest. On a 3-lane road that dip runs straight down the middle
        /// lane, so the centre lane visibly sinks and the outer lanes read as raised
        /// kerbs — which is exactly how it looked. It also carries no markings at the
        /// lane boundaries, only one stripe down its centre.
        ///
        /// A road tile is a flat rectangle. Generating it gives a guaranteed-planar
        /// surface at y = 0, dashes exactly on the lane boundaries, pavements at a
        /// deliberate height, and it costs 6 quads instead of a 200-unit imported mesh.
        /// The "everything from packs" rule is about *art*; a flat quad is geometry, and
        /// the pack mesh actively cannot express a correct 3-lane road.
        /// </summary>
        private static bool BuildRoadTile(string name, string fbxPath)
        {
            string path = $"{Root}/Road/{name}.prefab";
            if (Exists(path)) return false;

            GameObject root = NewRoot(name);

            float half = RoadTileWidth * 0.5f;          // 6
            float driveHalf = Gameplay.LaneModel.LaneWidth * 1.5f;   // 4.5 — outer lane edge

            // Driving surface: one flat quad at exactly y = 0, spanning the full tile.
            MakeQuad(root, "Asphalt", new Vector3(0f, 0f, 0f),
                     new Vector2(driveHalf * 2f, RoadTileWidth), MaterialLibrary.Asphalt());

            // Pavements either side, raised so they read as kerbs the car cannot drive on.
            float pavementWidth = half - driveHalf;      // 1.5
            float pavementCentre = driveHalf + pavementWidth * 0.5f;
            MakeKerb(root, "Pavement_L", -pavementCentre, pavementWidth);
            MakeKerb(root, "Pavement_R", +pavementCentre, pavementWidth);

            // Grass verges running out to the building line.
            //
            // Without these the world simply stops at x = +-6 and every building beyond
            // it hangs over the skybox — which is what "the buildings float" actually
            // was. It is not a Y offset: there is no ground under them at all. The verge
            // has to reach past the furthest building (sideOffset + jitter) or the seam
            // is just pushed further out instead of being closed.
            float vergeInner = half;
            float vergeOuter = GroundHalfWidth;
            float vergeWidth = vergeOuter - vergeInner;
            float vergeCentre = vergeInner + vergeWidth * 0.5f;
            MakeQuad(root, "Grass_L", new Vector3(-vergeCentre, PavementHeight, 0f),
                     new Vector2(vergeWidth, RoadTileWidth), MaterialLibrary.Grass());
            MakeQuad(root, "Grass_R", new Vector3(+vergeCentre, PavementHeight, 0f),
                     new Vector2(vergeWidth, RoadTileWidth), MaterialLibrary.Grass());

            BuildLaneMarkings(root);

            // Road is scenery; no collider. The player is held on a fixed Y.
            return Save(root, path);
        }

        /// <summary>Height of the pavement above the road surface.</summary>
        public const float PavementHeight = 0.18f;

        /// <summary>
        /// Half-width of the whole ground plate, road + pavement + grass verge.
        ///
        /// Must exceed the furthest scenery placement (`ScenerySpawner.sideOffset` +
        /// `sideOffsetJitter`, currently 13) AND the furthest back-row placement
        /// (`backRowOffset + backRowOffsetJitter`, currently 22 + 5 = 27) or buildings
        /// spawn past the edge of the world and hang over the skybox. 32 leaves headroom
        /// for both rows so the horizon reads as continuous ground rather than a strip the
        /// camera can see the end of.
        /// </summary>
        public const float GroundHalfWidth = 32f;

        /// <summary>
        /// A raised pavement slab: a top face at <see cref="PavementHeight"/> plus a
        /// vertical face along its inner edge, so the kerb has visible thickness from the
        /// player's low camera rather than looking like a painted stripe.
        /// </summary>
        private static void MakeKerb(GameObject root, string name, float centreX, float width)
        {
            MakeQuad(root, name, new Vector3(centreX, PavementHeight, 0f),
                     new Vector2(width, RoadTileWidth), MaterialLibrary.Pavement());

            // Inner vertical face, turned to face the road.
            float innerX = centreX > 0f ? centreX - width * 0.5f : centreX + width * 0.5f;
            var face = new GameObject(name + "_Face", typeof(MeshFilter), typeof(MeshRenderer));
            face.transform.SetParent(root.transform, false);
            face.transform.localPosition = new Vector3(innerX, PavementHeight * 0.5f, 0f);
            face.transform.localRotation = Quaternion.Euler(0f, 0f, centreX > 0f ? 90f : -90f);

            var mesh = QuadMesh(name + "_Face", new Vector2(PavementHeight, RoadTileWidth));
            face.GetComponent<MeshFilter>().sharedMesh = mesh;
            face.GetComponent<MeshRenderer>().sharedMaterial = MaterialLibrary.Pavement();
        }

        /// <summary>A flat, upward-facing quad parented to <paramref name="root"/>.</summary>
        private static void MakeQuad(GameObject root, string name, Vector3 localPosition, Vector2 size, Material material)
        {
            var go = new GameObject(name, typeof(MeshFilter), typeof(MeshRenderer));
            go.transform.SetParent(root.transform, false);
            go.transform.localPosition = localPosition;

            go.GetComponent<MeshFilter>().sharedMesh = QuadMesh(name, size);
            go.GetComponent<MeshRenderer>().sharedMaterial = material;
        }

        /// <summary>An XZ-plane quad of the given size, centred on its origin, facing +Y.</summary>
        private static Mesh QuadMesh(string name, Vector2 size)
        {
            float hx = size.x * 0.5f, hz = size.y * 0.5f;
            var mesh = new Mesh
            {
                name = name,
                vertices = new[]
                {
                    new Vector3(-hx, 0f, -hz), new Vector3(-hx, 0f, hz),
                    new Vector3(hx, 0f, hz),   new Vector3(hx, 0f, -hz),
                },
                triangles = new[] { 0, 1, 2, 0, 2, 3 },
                normals = new[] { Vector3.up, Vector3.up, Vector3.up, Vector3.up },
                uv = new[] { Vector2.zero, Vector2.up, Vector2.one, Vector2.right },
            };
            mesh.RecalculateBounds();
            return mesh;
        }

        // ==================================================================
        // Generated power-up meshes — REMOVED (were proc-gen).
        //
        // The previous proc-gen meshes (horseshoe / X-cross / hex shield / bolt /
        // snowflake) read as flat low-poly shapes at game speed and were retired in
        // favour of real Quaternius RPG Assets (Heart, Star, Armor_Metal,
        // Arrow_Golden, Snowflake3 + Potion6_Filled for fuel). They ship as FBX under
        // Assets/Models/Quaternius/RPG/ and are wired in BuildPowerUps /
        // BuildFuelPrefab below. The mesh-builder block that lived here was deleted
        // in this pass — the slab/box helpers (AddSlab/AddSlabAlong/AddBoxTris) were
        // only used by those generators and were removed with them.
        // ==================================================================

        /// <summary>
        /// Builds the lane markings at the lane boundaries, plus solid edge lines at the
        /// outside of the drivable surface.
        ///
        /// The source mesh only carries a single marking down its centre, which on a
        /// 3-lane road sits in the middle of the centre lane — so the road reads as one
        /// wide strip with a stripe through it rather than as three lanes. The dividers
        /// belong at the lane BOUNDARIES (x = +-1.5 for LaneModel.LaneWidth = 3), and the
        /// dashes have to be built here because no mesh in the pack has them.
        ///
        /// Quads rather than cubes: a lane marking is painted onto the road, it has no
        /// thickness, and a quad is 2 triangles against a cube's 12.
        /// </summary>
        private static void BuildLaneMarkings(GameObject root)
        {
            Material paint = MaterialLibrary.RoadLine();

            // Lane boundaries: between lane 0/1 and lane 1/2.
            float halfLane = Gameplay.LaneModel.LaneWidth * 0.5f;
            BuildDashedLine(root, -halfLane, paint);
            BuildDashedLine(root, +halfLane, paint);

            // Solid lines at the outer edge of the drivable area.
            float edge = Gameplay.LaneModel.LaneWidth * 1.5f;
            BuildSolidLine(root, -edge, paint);
            BuildSolidLine(root, +edge, paint);
        }

        private const float MarkingWidth = 0.16f;
        private const float MarkingLift = 0.012f;   // clear of the road to beat z-fighting
        private const float DashLength = 2.2f;
        private const float DashGap = 1.8f;

        private static void BuildDashedLine(GameObject root, float x, Material paint)
        {
            float tile = RoadTileWidth;
            float stride = DashLength + DashGap;
            int count = Mathf.Max(1, Mathf.RoundToInt(tile / stride));
            // Recompute the stride from the rounded count so dashes meet seamlessly across
            // the tile join instead of drifting out of phase every tile.
            stride = tile / count;

            for (int i = 0; i < count; i++)
            {
                float z = -tile * 0.5f + stride * (i + 0.5f);
                MakeMarkingQuad(root, $"Dash_{x:0.0}_{i}", new Vector3(x, MarkingLift, z),
                                new Vector2(MarkingWidth, DashLength), paint);
            }
        }

        private static void BuildSolidLine(GameObject root, float x, Material paint)
        {
            MakeMarkingQuad(root, $"EdgeLine_{x:0.0}", new Vector3(x, MarkingLift, 0f),
                            new Vector2(MarkingWidth, RoadTileWidth), paint);
        }

        /// <summary>A flat, upward-facing quad of the given size, centred on <paramref name="position"/>.</summary>
        private static void MakeMarkingQuad(GameObject root, string name, Vector3 position, Vector2 size, Material paint)
        {
            MakeQuad(root, name, position, size, paint);
        }

        private static void BuildSceneryBatch(ref int built)
        {
            // Front-row skyline — the dense, varied mid-height wall that sells speed.
            // Measured (in pack units, before buildingScale): standard commercial a..n span
            // ~0.9 x 1.3 x 0.9 up to ~2.3 x 2.5 x 1.8; industrial runs a bit larger and
            // blockier. Building all of them costs ~40 prefabs (~a few hundred KB each vs a
            // 25 MB brotli budget) and the spawner's weighted pick keeps the skyline lively
            // instead of recycling the same three silhouettes.
            string[] commercial = { "building-a", "building-b", "building-c", "building-d", "building-e", "building-f", "building-g", "building-h", "building-i", "building-j", "building-k", "building-l", "building-m", "building-n" };
            foreach (string id in commercial)
                built += BuildScenery($"Scenery_{id}", $"{Kenney}/CityKitCommercial/{id}.fbx") ? 1 : 0;

            string[] industrial = { "building-a", "building-b", "building-c", "building-d", "building-e", "building-f", "building-g", "building-h", "building-i", "building-j", "building-k", "building-l", "building-m", "building-n" };
            foreach (string id in industrial)
                built += BuildScenery($"Scenery_ind-{id}", $"{Kenney}/CityKitIndustrial/{id}.fbx") ? 1 : 0;

            // Industrial continues into o..t + chimneys + tank — heavier/blockier than
            // commercial, useful as a mid-back silhouette where the front row breaks.
            string[] industrialFar = { "building-o", "building-p", "building-q", "building-r", "building-s", "building-t" };
            foreach (string id in industrialFar)
                built += BuildScenery($"Scenery_ind-{id}", $"{Kenney}/CityKitIndustrial/{id}.fbx") ? 1 : 0;

            // Tall focal points for the back row. Measured: skyscrapers ~1.3 x 4.1 x 1.3,
            // i.e. 3x the height of a standard commercial block, so at backRowScale ~7 they
            // tower above the front row instead of blending into it. b/d were missing in an
            // earlier pass; BuildScenery skips missing files with a warning, safe to list.
            string[] skyscrapers = { "skyscraper-a", "skyscraper-b", "skyscraper-c", "skyscraper-d", "skyscraper-e" };
            foreach (string id in skyscrapers)
                built += BuildScenery($"Scenery_skyscraper-{id}", $"{Kenney}/CityKitCommercial/building-{id}.fbx") ? 1 : 0;

            // Low-detail towers: thin (~0.5 wide) and varied in height (0.7..2.0). Used as a
            // sparse *backfill* between the front row and the skyscrapers so the horizon isn't
            // a hard wall — three thin towers in the distance read as a neighbourhood beyond
            // the focal buildings without competing for the eye.
            string[] lowDetail = { "low-detail-building-a", "low-detail-building-b", "low-detail-building-c", "low-detail-building-d", "low-detail-building-e", "low-detail-building-f", "low-detail-building-g", "low-detail-building-h", "low-detail-building-i", "low-detail-building-j", "low-detail-building-k", "low-detail-building-l", "low-detail-building-m", "low-detail-building-n" };
            foreach (string id in lowDetail)
                built += BuildScenery($"Scenery_{id}", $"{Kenney}/CityKitCommercial/{id}.fbx") ? 1 : 0;

            // Industrial chimneys: tall thin verticals that puncture the skyline and add a
            // distinct silhouette vs the boxy commercial back row. The tank is a low, wide
            // form good for the verge between buildings.
            foreach (string id in new[] { "chimney-basic", "chimney-large", "chimney-medium", "chimney-small", "detail-tank" })
                built += BuildScenery($"Scenery_ind-{id}", $"{Kenney}/CityKitIndustrial/{id}.fbx") ? 1 : 0;

            built += BuildScenery("Prop_Streetlight", $"{Quaternius}/ModularStreets/Streetlight_Single.fbx", MaterialLibrary.Metal(), scale: StreetlightScale, upright: true) ? 1 : 0;
            built += BuildScenery("Prop_Tree", $"{Quaternius}/SimpleNature/Tree1.fbx", MaterialLibrary.Foliage(), scale: TreeScale, upright: true) ? 1 : 0;
            built += BuildScenery("Prop_Bush", $"{Quaternius}/SimpleNature/Bush1.fbx", MaterialLibrary.Foliage(), scale: BushScale, upright: true) ? 1 : 0;
        }

        /// <summary>
        /// Character meshes offered as pedestrians. The "Smooth_" variants of the same
        /// packs are higher-poly duplicates — skipped, because a WebGL build under a
        /// 25 MB budget has no use for two versions of the same silhouette at the roadside.
        /// </summary>
        public static readonly (string Name, string Fbx)[] PedestrianModels =
        {
            ("Ped_Male_Casual",      "AnimatedMen/Male_Casual.fbx"),
            ("Ped_Male_Shirt",       "AnimatedMen/Male_Shirt.fbx"),
            ("Ped_Male_Suit",        "AnimatedMen/Male_Suit.fbx"),
            ("Ped_Male_LongSleeve",  "AnimatedMen/Male_LongSleeve.fbx"),
            ("Ped_Female_Casual",    "AnimatedWomen/Female_Casual.fbx"),
            ("Ped_Female_Dress",     "AnimatedWomen/Female_Dress.fbx"),
            ("Ped_Female_TankTop",   "AnimatedWomen/Female_TankTop.fbx"),
            ("Ped_Female_Alt",       "AnimatedWomen/Female_Alternative.fbx"),
        };

        /// <summary>
        /// The character packs are the exception to the Quaternius x100 rule: they are
        /// authored at metre scale already. Measured in the editor, <c>Male_Casual</c>
        /// imports at <b>1.96 x 4.93 x 1.13</b> and is already upright, so 1.8/4.93
        /// gives a ~1.8 m pedestrian. <see cref="ModelAxisFixer"/> exempts these folders
        /// from the prop import scale for the same reason.
        /// </summary>
        private const float PedestrianScale = 0.36518f;

        private static void BuildPedestrianBatch(ref int built)
        {
            MaterialLibrary.EnsureFolder($"{Root}/Pedestrians");
            foreach (var (name, fbx) in PedestrianModels)
                built += BuildPedestrian(name, $"{Quaternius}/{fbx}") ? 1 : 0;
        }

        /// <summary>
        /// Builds (or returns the existing) AnimatorController for a given character FBX,
        /// with a single "Walk" state looping this FBX's own embedded <c>Man_Walk</c> /
        /// <c>Female_Walk</c> clip.
        ///
        /// One controller per FBX rather than one shared controller because the character
        /// packs are imported as <b>Generic</b> rigs (see <see cref="ModelAxisFixer"/>) and
        /// Generic clips are bound to their source rig's Avatar — playing <c>Man_Walk</c>
        /// on a <c>Female_CasualAvatar</c> would not retarget the way a Humanoid clip
        /// would, since the bone hierarchies are technically separate even if structurally
        /// similar. To stay correct under Generic, every FBX gets its own controller that
        /// references its own walk clip, paired with the FBX's own Avatar on the Animator.
        ///
        /// Walk clip lookup by name suffix: the Quaternius character pack names its clips
        /// <c>HumanArmature|Man_Walk</c> for the AnimatedMen folder and
        /// <c>HumanArmature|Female_Walk</c> for the AnimatedWomen folder, so we look for
        /// any clip whose name ends in <c>|Man_Walk</c> or <c>|Female_Walk</c> regardless
        /// of the package name preceding the bar. Any preview<nbsp>clip (<c>__preview__</c>)
        /// is excluded.
        ///
        /// Idempotent: the controller is a saved asset, so re-running setup leaves it
        /// alone (the existence check skips the build).
        /// </summary>
        private static RuntimeAnimatorController EnsureWalkController(string fbxPath)
        {
            string leafName = Path.GetFileNameWithoutExtension(fbxPath);
            string controllerPath = $"Assets/Animations/PedestrianWalk_{leafName}.controller";

            var existing = AssetDatabase.LoadAssetAtPath<RuntimeAnimatorController>(controllerPath);
            if (existing != null) return existing;

            MaterialLibrary.EnsureFolder("Assets/Animations");

            AnimationClip walkClip = null;
            foreach (var sub in AssetDatabase.LoadAllAssetsAtPath(fbxPath))
            {
                if (!(sub is AnimationClip c)) continue;
                if (c.name.StartsWith("__preview__")) continue;
                if (c.name.EndsWith("|Man_Walk") || c.name.EndsWith("|Female_Walk"))
                {
                    walkClip = c;
                    break;
                }
            }
            if (walkClip == null)
            {
                Debug.LogWarning($"[PrefabsBuilder] Walk clip not found inside {fbxPath} — " +
                                 "pedestrian will spawn idle. Run GDG Go > 5c. Clear Quaternius Axis Bake first.");
                return null;
            }

            AnimatorController controller = AnimatorController.CreateAnimatorControllerAtPath(controllerPath);
            if (controller == null) return null;

            var rootStateMachine = controller.layers.Length > 0 ? controller.layers[0].stateMachine : null;
            if (rootStateMachine == null) return null;

            var walkState = rootStateMachine.AddState("Walk");
            walkState.motion = walkClip;
            rootStateMachine.defaultState = walkState;

            EditorUtility.SetDirty(controller);
            AssetDatabase.SaveAssets();
            Debug.Log($"[PrefabsBuilder] Built {leafName} walk controller using {walkClip.name}.");
            return controller;
        }

        /// <summary>
        /// Loads the Avatar sub-asset that Unity auto-generates for a Humanoid FBX import,
        /// so the prefab's Animator can be bound to the correct rig. Each character FBX's
        /// avatar carries its own retargeting mapping — even within the Quaternius pack
        /// (male vs female), so we look it up per FBX rather than sharing.
        /// </summary>
        private static Avatar LoadAvatarFor(string fbxPath)
        {
            foreach (var sub in AssetDatabase.LoadAllAssetsAtPath(fbxPath))
            {
                if (sub is Avatar av && !string.IsNullOrEmpty(av.name)) return av;
            }
            return null;
        }

        private static bool BuildPedestrian(string name, string fbxPath)
        {
            string path = $"{Root}/Pedestrians/{name}.prefab";
            if (Exists(path)) return false;

            GameObject root = NewRoot(name);
            GameObject mesh = AttachMesh(root, fbxPath, scale: PedestrianScale);
            if (mesh == null) { Object.DestroyImmediate(root); return false; }

            // These meshes name their slots after the body part, so each pedestrian can
            // be dressed properly instead of being one flat colour.
            MaterialLibrary.AssignNamedPalette(mesh,
                new System.Collections.Generic.Dictionary<string, Material>
                {
                    { "Skin",  MaterialLibrary.Skin() },
                    { "Hair",  MaterialLibrary.GetOrCreate($"{MaterialLibrary.WorldFolder}/Hair.mat", new Color(0.16f, 0.12f, 0.10f), 0.2f, 0f) },
                    { "Eyes",  MaterialLibrary.GetOrCreate($"{MaterialLibrary.WorldFolder}/Eyes.mat", new Color(0.10f, 0.10f, 0.12f), 0.6f, 0f) },
                    { "Shirt", MaterialLibrary.Clothing() },
                    { "Pants", MaterialLibrary.GetOrCreate($"{MaterialLibrary.WorldFolder}/Pants.mat", new Color(0.22f, 0.24f, 0.32f), 0.05f, 0f) },
                    { "Shoes", MaterialLibrary.GetOrCreate($"{MaterialLibrary.WorldFolder}/Shoes.mat", new Color(0.12f, 0.11f, 0.10f), 0.3f, 0f) },
                    { "Socks", MaterialLibrary.GetOrCreate($"{MaterialLibrary.WorldFolder}/Socks.mat", new Color(0.80f, 0.80f, 0.78f), 0.05f, 0f) },
                },
                fallback: MaterialLibrary.Clothing());

            // PedestrianNPC.OnTriggerEnter charges Heat when the player mounts the kerb,
            // so it needs a trigger to receive that message at all. Sized to a person
            // rather than fitted to the mesh: the T-pose these characters ship in has the
            // arms out wide, and a bounds-fitted box would be about as wide as it is tall.
            var collider = root.AddComponent<CapsuleCollider>();
            collider.isTrigger = true;
            collider.height = 1.8f;
            collider.radius = 0.3f;
            collider.center = new Vector3(0f, 0.9f, 0f);

            root.AddComponent<Pedestrians.PedestrianNPC>();

            // Drive the walk cycle. The Quaternius character FBX importer has been
            // configured (by ModelAxisFixer) to a Generic rig with an auto-generated
            // Generic Avatar, and a per-FBX PedestrianWalk controller plays this FBX's
            // own embedded Man_Walk / Female_Walk clip. Without an Animator, the
            // pedestrian spawned in T-pose and slid along Z — set the controller here
            // so they walk from spawn.
            var animator = root.AddComponent<Animator>();
            animator.applyRootMotion = false;
            animator.cullingMode = AnimatorCullingMode.AlwaysAnimate;
            animator.avatar = LoadAvatarFor(fbxPath);
            // The NPC field is what PedestrianNPC.SetWalking hooks to; route it now so
            // runtime doesn't have to look it up.
            var npc = root.GetComponent<Pedestrians.PedestrianNPC>();
            if (npc != null) npc.animator = animator;
            var controller = EnsureWalkController(fbxPath);
            if (controller != null) animator.runtimeAnimatorController = controller;

            // Streamed and moving, so it needs a kinematic body like every other
            // streamed collider — see MakeMovingTrigger.
            MakeMovingTrigger(root);

            return Save(root, path);
        }

        private static bool BuildScenery(string name, string fbxPath, Material palette = null, float scale = 1f, bool upright = false)
        {
            string path = $"{Root}/Scenery/{name}.prefab";
            if (Exists(path)) return false;

            GameObject root = NewRoot(name);
            GameObject mesh = AttachMesh(root, fbxPath, scale, upright);
            if (mesh == null) { Object.DestroyImmediate(root); return false; }

            if (palette != null) MaterialLibrary.AssignPalette(mesh, palette);

            // Scenery never has colliders — it exists only to sell speed.
            return Save(root, path);
        }

        // ==================================================================
        // Helpers
        // ==================================================================

        private static bool Exists(string path) => AssetDatabase.LoadAssetAtPath<GameObject>(path) != null;

        private static GameObject NewRoot(string name) => new GameObject(name);

        /// <summary>
        /// Adds a kinematic Rigidbody to anything that both has a collider and moves.
        ///
        /// Every streamed object is repositioned every frame. A collider with no
        /// Rigidbody is a <i>static</i> collider, and moving one makes PhysX rebuild its
        /// static broadphase — with a few hundred coins and obstacles in flight that is a
        /// per-frame cost the WebGL build cannot absorb. A kinematic Rigidbody moves them
        /// into the dynamic broadphase, which is what it is designed for, and still sends
        /// trigger messages against the player's kinematic trigger collider.
        /// </summary>
        /// <summary>
        /// Sizes a trigger to the renderer bounds of the mesh under it, in the root's
        /// local space, so the hitbox matches what the player sees.
        ///
        /// Falls back to <paramref name="fallback"/> when the mesh has no renderers,
        /// rather than leaving a zero-size collider that nothing can ever hit.
        ///
        /// The bounds are shrunk slightly on X/Z: renderer bounds are an axis-aligned box
        /// around the whole mesh, so for anything round or angled the corners enclose a
        /// lot of empty air. Trimming keeps a near-miss feeling like a near-miss instead
        /// of a phantom collision.
        /// </summary>
        private static void FitTriggerToMesh(BoxCollider collider, GameObject mesh, Vector3 fallback)
        {
            if (collider == null) return;

            var renderers = mesh != null ? mesh.GetComponentsInChildren<Renderer>(true) : null;
            if (renderers == null || renderers.Length == 0)
            {
                collider.size = fallback;
                collider.center = new Vector3(0f, fallback.y * 0.5f, 0f);
                return;
            }

            Bounds bounds = renderers[0].bounds;
            for (int i = 1; i < renderers.Length; i++) bounds.Encapsulate(renderers[i].bounds);

            // Renderer.bounds is world space; the prefab root sits at the origin while
            // being built, so world == local here.
            Vector3 size = bounds.size;
            Vector3 centre = bounds.center;

            const float lateralTrim = 0.82f;
            size.x = Mathf.Max(0.2f, size.x * lateralTrim);
            size.z = Mathf.Max(0.2f, size.z * lateralTrim);
            size.y = Mathf.Max(0.2f, size.y);

            collider.size = size;
            collider.center = centre;
        }

        private static void MakeMovingTrigger(GameObject root)
        {
            var body = root.GetComponent<Rigidbody>();
            if (body == null) body = root.AddComponent<Rigidbody>();
            body.isKinematic = true;
            body.useGravity = false;
            // Nothing here is simulated, so skip the interpolation and sleep bookkeeping.
            body.interpolation = RigidbodyInterpolation.None;
            body.collisionDetectionMode = CollisionDetectionMode.Discrete;
        }

        /// <summary>
        /// Instantiates an imported FBX as a child named "Mesh". Returns null (with a
        /// warning) when the model is missing, so one absent file cannot abort the batch.
        /// </summary>
        /// <summary>
        /// Shifts a mesh child down so the TOP of its bounds sits on y = 0.
        ///
        /// Used only by the road: it is the surface everything else stands on, so the
        /// plane the player drives at has to be y = 0. Props use the opposite alignment
        /// (bottom on the ground) which <see cref="AttachMesh"/> applies by default.
        /// </summary>
        private static void AlignTopSurfaceToGround(GameObject mesh)
        {
            if (mesh == null) return;

            var renderers = mesh.GetComponentsInChildren<Renderer>(true);
            if (renderers.Length == 0) return;

            Bounds b = renderers[0].bounds;
            for (int i = 1; i < renderers.Length; i++) b.Encapsulate(renderers[i].bounds);

            Vector3 p = mesh.transform.localPosition;
            p.y -= b.max.y;
            mesh.transform.localPosition = p;
        }

        private static GameObject AttachMesh(GameObject root, string fbxPath, float scale,
                                             bool upright = false, Quaternion? rotation = null)
        {
            var model = AssetDatabase.LoadAssetAtPath<GameObject>(fbxPath);
            if (model == null)
            {
                Debug.LogWarning($"[PrefabsBuilder] Missing model: {fbxPath} — skipping {root.name}.");
                return null;
            }

            var instance = (GameObject)PrefabUtility.InstantiatePrefab(model);
            if (instance == null)
            {
                Debug.LogWarning($"[PrefabsBuilder] Could not instantiate {fbxPath}.");
                return null;
            }

            instance.name = "Mesh";
            instance.transform.SetParent(root.transform, false);
            instance.transform.localPosition = Vector3.zero;
            // Z-up sources are stood up here rather than at each call site, and only ever
            // on the mesh child so the root's collider stays axis-aligned.
            instance.transform.localRotation = rotation ?? (upright ? QuaterniusUprightRotation : Quaternion.identity);
            instance.transform.localScale = Vector3.one * scale;

            // The mesh child may be rotated (Z-up sources) or have a centred
            // pivot (some Kenney props authored around the origin rather than
            // at the ground), so its own bounds can be offset from the root
            // after parenting. If the lowest point now sits below y = 0,
            // drop it so the object does not render half-buried under the
            // scene. This only fires when actually needed — props authored
            // with their base at the origin already have min.y = 0 and are
            // left untouched (preserves the existing player-car / cone / etc.
            // alignment behaviour from pre-power-up-import).
            {
                var renderers = instance.GetComponentsInChildren<Renderer>(true);
                if (renderers.Length > 0)
                {
                    Bounds b = renderers[0].bounds;
                    for (int i = 1; i < renderers.Length; i++) b.Encapsulate(renderers[i].bounds);
                    if (b.min.y < -0.0001f)
                        instance.transform.localPosition = new Vector3(0f, -b.min.y, 0f);
                }
            }
            return instance;
        }

        /// <summary>
        /// Assigns a tag, warning instead of throwing if it is not registered.
        /// <c>ProjectSetup.EnsureTags</c> is called first so this should never fire — the
        /// guard exists because an unregistered tag previously threw and killed the batch.
        /// </summary>
        private static void SafeSetTag(GameObject go, string tag)
        {
            try
            {
                go.tag = tag;
            }
            catch (UnityException)
            {
                Debug.LogWarning($"[PrefabsBuilder] Tag \"{tag}\" is not registered. " +
                                 "Run \"GDG Go > 1. Project Setup\", or add it under " +
                                 "Edit > Project Settings > Tags and Layers.");
            }
        }

        private static bool Save(GameObject root, string path)
        {
            // Meshes generated in code (the road surface and lane markings) live only in
            // memory, so the saved prefab would reference assets that were never written
            // and load with nothing to draw.
            //
            // AddObjectToAsset AFTER SaveAsPrefabAsset does not work: the prefab has
            // already serialised its MeshFilter references by then, so the meshes end up
            // stored in the file while every filter still points at nothing. Verified —
            // the asset held all 13 meshes and every renderer measured zero size.
            //
            // The fix is to write the meshes as their own asset FIRST, so they have a real
            // asset path before the prefab is serialised and the references resolve.
            var generated = new List<Mesh>();
            foreach (var filter in root.GetComponentsInChildren<MeshFilter>(true))
            {
                Mesh mesh = filter.sharedMesh;
                if (mesh == null) continue;
                if (!string.IsNullOrEmpty(AssetDatabase.GetAssetPath(mesh))) continue;   // already an asset
                generated.Add(mesh);
            }

            if (generated.Count > 0)
            {
                string meshPath = Path.ChangeExtension(path, null) + "_Meshes.asset";
                AssetDatabase.CreateAsset(generated[0], meshPath);
                for (int i = 1; i < generated.Count; i++)
                    AssetDatabase.AddObjectToAsset(generated[i], generated[0]);
                AssetDatabase.SaveAssets();
            }

            PrefabUtility.SaveAsPrefabAsset(root, path);
            Object.DestroyImmediate(root);
            Debug.Log($"[PrefabsBuilder] Built {path}");
            return true;
        }
    }
}
