using UnityEngine;

namespace GDGGo.Supabase
{
    /// <summary>
    /// Holds the run identity, player label, and vehicle configuration passed from the
    /// hosting website wrapper. Authentication remains in the parent page; no JWT is
    /// exposed to the embedded Unity frame.
    /// </summary>
    public sealed class SupabaseSession : MonoBehaviour
    {
        public static SupabaseSession Instance { get; private set; }

        /// <summary>Cached display name from the users table or URL query.</summary>
        public string DisplayName { get; private set; }

        /// <summary>Cached username from signup/signin or URL query.</summary>
        public string Username { get; private set; }

        /// <summary>Selected car body ID (e.g. 'SportsCar', 'SUV', 'Taxi') passed from the website.</summary>
        public string CarId { get; private set; }

        /// <summary>Stable UUID generated by the host for this single run.</summary>
        public string RunId { get; private set; }

        private void Awake()
        {
            if (Instance != null && Instance != this)
            {
                Destroy(gameObject);
                return;
            }
            Instance = this;
            DontDestroyOnLoad(gameObject);
            InitFromUrlQuery();
        }

        private void OnDestroy()
        {
            if (Instance == this) Instance = null;
        }

        /// <summary>
        /// Reads ?run=&amp;u=&amp;dn=&amp;car= from <see cref="Application.absoluteURL"/> in WebGL builds.
        /// </summary>
        public void InitFromUrlQuery()
        {
            string url = Application.absoluteURL;
            if (string.IsNullOrEmpty(url)) return;

            try
            {
                int queryIdx = url.IndexOf('?');
                if (queryIdx >= 0 && queryIdx < url.Length - 1)
                {
                    string query = url.Substring(queryIdx + 1);
                    string[] pairs = query.Split('&');
                    foreach (string pair in pairs)
                    {
                        string[] kv = pair.Split(new[] { '=' }, 2);
                        if (kv.Length == 2)
                        {
                            string key = System.Uri.UnescapeDataString(kv[0]);
                            string val = System.Uri.UnescapeDataString(kv[1]);
                            if (key == "run") RunId = val;
                            else if (key == "u") Username = val;
                            else if (key == "dn") DisplayName = val;
                            else if (key == "car") CarId = val;
                        }
                    }
                    Debug.Log($"[SupabaseSession] Parsed URL query: user={Username}, car={CarId}, run={RunId}");
                }
            }
            catch (System.Exception ex)
            {
                Debug.LogWarning("[SupabaseSession] Failed to parse URL query: " + ex.Message);
            }
        }

        /// <summary>Clears the in-memory session.</summary>
        public void Clear()
        {
            Username = null;
            DisplayName = null;
            CarId = null;
            RunId = null;
            Debug.Log("[Supabase] Session cleared.");
        }
    }
}
